### ISSUE TITLE
Could not find `https://github.com/nickelc/frigg.git` in registry `crates-io`

### ISSUE THREAD

**Issue by languagemaniac** [nickelc/frigg#1]
Hi, I'm trying to install frigg but I get this error:

error: could not find `https://github.com/nickelc/frigg.git` in registry `crates-io` with version `*`

I don't know if it's an error on my side or on yours. Could you help me?

**Comment by nickelc** [comment]
oh sorry, the command is `cargo install --git https://github.com/nickelc/frigg`.

**Comment by languagemaniac** [comment]
Got it, now it's installing fine. Thanks!
